### ISSUE TITLE
Translate "history" in the pencil icon menu.

### ISSUE THREAD

**Issue by ktrvs** [ediblewiki/ScratchWikiSkin2#3]
The "history" option in the pencil icon menu should be changed to "meal history".

Assigning all the @ediblewiki/translators.

**Comment by Kenny2github** [comment]
This isn't a SWS/EWS bug, just edit MediaWiki:Scratchwikiskin2-view-history. In the future, when you want to change interface text, please add `?uselang=qqx` to the end of the URL address to see the message keys.

**Comment by duckboycool** [comment]
I actually left that as history intentionally when translating. But you could keep it changed.
